version: 2.1


jobs:
  build:
    docker:
      - image: node:18 # Use the desired Python version
    steps:
      - checkout
      - run: npm i
      - run: npm run build

  test:
    docker:
      - image: node:18
    steps: 
      - checkout


  # deploy:
  #   docker:
  #     - image: python:3.11
  #   steps: 
  #     - checkout




workflows:
  s3-example:
    jobs:
      - test
      - build:
          requires:
            - test

